- name: Preparing Workstation
  become: yes
  hosts: localhost
  connection: local
  roles:
    - linux_apps
    - docker
    - brave
    - virtualbox
    - hashicorp_apps

- name: Configure user data
  hosts: localhost
  connection: local
  roles:
    - zsh
    - tor
    - vscode
