---
- name: Add non-free repository
  apt_repository:
    repo: deb http://deb.debian.org/debian/ bookworm main contrib non-free non-free-firmware

- name: Installing Linux Apps
  become: true
  apt:
    name: '{{ item }}'
    install_recommends: yes
    state: present
  loop: "{{ linux_apps }}"

- name: Install deb package from source
  apt:
    deb: '{{ item }}'
    state: present
  loop: "{{ deb_packages }}"