---
- name: Install Oracle VirtualBox Key
  become: true
  apt_key:
    url: 'https://www.virtualbox.org/download/oracle_vbox_2016.asc'
    state: present
  
- name: Install Oracle VirtualBox Repository
  become: true
  apt_repository:
    repo: 'deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian bookworm contrib'
    state: present
    filename: vbox

- name: Install Oracle VirtualBox
  become: true
  apt:
    name: virtualbox-7.0