---
- name: Download tor browser
  become: true
  get_url: 
    url: "https://dist.torproject.org/torbrowser/13.0.1/tor-browser-linux-x86_64-13.0.1.tar.xz"
    dest: /tmp/tor-browser.tar.xz
    mode: 0777

- name: Descompactar o arquivo
  unarchive:
    src: /tmp/tor-browser.tar.xz
    dest: "{{ ansible_env.HOME }}/"
    remote_src: yes
    
- name: Criar um atalho para o Tor Browser
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: 'alias tor="sh -c {{ ansible_env.HOME }}/tor-browser/Browser/start-tor-browser --detach"'
    state: present
    create: yes

- name: Reload Bash Configuration
  command: source ~/.zshrc
  ignore_errors: true